### ISSUE TITLE
Pulling Datasource fails

### ISSUE THREAD

**Issue by mms-gianni** [grafana/grizzly#207]
I try to pull the Datasources, but it fails. Pulling the DashboardFolder and Dashboard resources works fine. 

Grafana Version : Grafana v7.1.0 (8101355285)

```
# grr --version
2022-03-10 10:13:00.516947 I | grr version v0.2.0-beta3
```

```
# grr providers
API VERSION                     KIND
grizzly.grafana.com/v1alpha1    Datasource
grizzly.grafana.com/v1alpha1    DashboardFolder
grizzly.grafana.com/v1alpha1    Dashboard
grizzly.grafana.com/v1alpha1    PrometheusRuleGroup
grizzly.grafana.com/v1alpha1    SyntheticMonitoringCheck
``` 

```
# grr pull -d resources -t "Datasource/*"
INFO[0000] Pulling resources from resources
DEBU[0000] Listing remote values for handler Datasource
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/grafana/grizzly/pkg/grafana.getRemoteDatasourceList(0x0, 0x0, 0x0, 0x0, 0x0)
	/drone/src/pkg/grafana/datasources.go:87 +0x6ce
github.com/grafana/grizzly/pkg/grafana.(*DatasourceHandler).ListRemote(0x38055a0, 0x5, 0x27cf556, 0x24, 0xc0007bfbd8, 0x1)
	/drone/src/pkg/grafana/datasource-handler.go:124 +0x25
github.com/grafana/grizzly/pkg/grizzly.Pull(0x7ff7bfeff804, 0x9, 0xc0002ea214, 0x4, 0x1, 0xc0005b7f80, 0x3, 0x3, 0xc0004370a0, 0x1, ...)
	/drone/src/pkg/grizzly/workflow.go:120 +0x2cf
main.pullCmd.func1(0xc000721360, 0xc0004af340, 0x1, 0x4, 0x0, 0x0)
	/drone/src/cmd/grr/workflow.go:70 +0xd6
main.initialiseLogging.func1(0xc000721360, 0xc0004af340, 0x1, 0x4, 0x0, 0x0)
	/drone/src/cmd/grr/workflow.go:244 +0xab
github.com/go-clix/cli.(*Command).execute(0xc000721360, 0xc0004af2c0, 0x4, 0x4, 0xc000721360, 0xc0004af2c0)
	/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:118 +0x34e
github.com/go-clix/cli.(*Command).Execute(0xc000491900, 0xc0007bff28, 0xa)
	/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:76 +0x105
main.main()
	/drone/src/cmd/grr/main.go:43 +0x24b
```

**Comment by mms-gianni** [comment]
I tried to reproduce the Issue with Grafana 8.4.0-beta and everything worked fine as expected.

Therefore i'm closing this issue.
