### ISSUE TITLE
[Bug]: grr serve doesn't work on mac and linux (arm and amd64)

### ISSUE THREAD

**Issue by xinity** [grafana/grizzly#503]
### Grizzly Version

0.4.8

### Expected Behavior

grr serve would start the local grr server without any error

### Actual Behavior

grr serve doesn't work and throws an error message like:
````
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.serveCmd.func1(0x1400042a500?, {0x104202aa0, 0x0, 0x0})
	/home/runner/work/grizzly/grizzly/cmd/grr/workflow.go:378 +0x3dc
main.initialiseOnlySpec.func1(0x14000425540, {0x104202aa0, 0x0, 0x0})
	/home/runner/work/grizzly/grizzly/cmd/grr/workflow.go:532 +0x74
main.initialiseLogging.func1(0x14000425540, {0x104202aa0, 0x0, 0x0})
	/home/runner/work/grizzly/grizzly/cmd/grr/workflow.go:547 +0x94
github.com/go-clix/cli.(*Command).execute(0x14000425540, {0x104202aa0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:118 +0x388
github.com/go-clix/cli.(*Command).Execute(0x1400036cf00)
	/home/runner/go/pkg/mod/github.com/go-clix/cli@v0.2.0/command.go:76 +0xc4
main.main()
	/home/runner/work/grizzly/grizzly/cmd/grr/main.go:73 +0x53c
```

### Steps to Reproduce

1. grr serve

**Comment by K-Phoen** [comment]
Hey!

Thanks for reporting this. #504 fixes your issue :)
